# Generated by Django 5.1.3 on 2024-11-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogDate', models.DateTimeField()),
                ('blogAuthor', models.CharField(max_length=255)),
                ('blogTitle', models.CharField(max_length=255)),
                ('blogTag', models.CharField(max_length=255)),
                ('blogText', models.TextField()),
                ('blogPhoto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
