# Generated by Django 5.1.3 on 2024-11-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_subcriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcriber',
            new_name='Subscriber',
        ),
    ]
