# Generated by Django 5.1.3 on 2024-11-16 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_subcriber_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blogPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photos/'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='dateSub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
