# Generated by Django 5.1.3 on 2024-11-19 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_blogentry_blogphoto_alter_subscriber_datesub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blogText',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
