# Generated by Django 5.1.3 on 2024-11-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_blogentry_blogtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='blogPublic',
            field=models.BooleanField(default=False),
        ),
    ]
